-- ============================================================
-- Catálogo de roupas - Estrutura PostgreSQL para Supabase
-- Compatível com os models atuais do projeto Flask/SQLAlchemy
-- ============================================================

begin;

-- 1. Administradores do painel
create table if not exists public.admin (
    id integer generated by default as identity primary key,
    username varchar(80) not null unique,
    password_hash varchar(255) not null
);

-- 2. Categorias configuráveis do catálogo
create table if not exists public.category (
    id integer generated by default as identity primary key,
    name varchar(80) not null unique,
    slug varchar(100) not null unique,
    description text default '',
    active boolean default true,
    sort_order integer default 0,
    created_at timestamp without time zone default now()
);

-- 3. Produtos exibidos no catálogo
create table if not exists public.product (
    id integer generated by default as identity primary key,
    name varchar(160) not null,
    slug varchar(180) not null unique,
    code varchar(60) not null unique,
    price double precision not null check (price >= 0),
    old_price double precision null check (old_price is null or old_price >= 0),
    category varchar(80) not null,
    brand varchar(80) not null,
    sizes varchar(120) default 'P,M,G',
    colors varchar(160) default 'Preto',
    material varchar(120) default 'Algodão',
    fit varchar(120) default 'Regular',
    gender varchar(40) default 'Unissex',
    description text default '',
    stock integer default 0 check (stock >= 0),
    status varchar(40) default 'Em estoque',
    featured boolean default false,
    launch boolean default false,
    active boolean default true,
    created_at timestamp without time zone default now()
);

-- 4. Imagens associadas aos produtos
create table if not exists public.product_image (
    id integer generated by default as identity primary key,
    url varchar(700) not null,
    path varchar(500) default '',
    product_id integer not null,
    constraint fk_product_image_product
        foreign key (product_id)
        references public.product(id)
        on delete cascade
);

-- Índices usados pelas páginas e filtros do catálogo
create index if not exists idx_category_active_order
    on public.category(active, sort_order, name);

create index if not exists idx_product_active
    on public.product(active);

create index if not exists idx_product_category
    on public.product(category);

create index if not exists idx_product_brand
    on public.product(brand);

create index if not exists idx_product_created_at
    on public.product(created_at desc);

create index if not exists idx_product_launch
    on public.product(launch)
    where active = true;

create index if not exists idx_product_featured
    on public.product(featured)
    where active = true;

create index if not exists idx_product_image_product_id
    on public.product_image(product_id);

-- Segurança para a Data API do Supabase.
-- O backend Flask conectado pela DATABASE_URL continua podendo administrar os dados.
alter table public.admin enable row level security;
alter table public.category enable row level security;
alter table public.product enable row level security;
alter table public.product_image enable row level security;

-- Nunca disponibilizar administradores pela API pública
revoke all on table public.admin from anon, authenticated;

-- Categorias públicas: somente leitura das categorias ativas
revoke all on table public.category from anon, authenticated;
grant select on table public.category to anon, authenticated;

drop policy if exists "Leitura pública de categorias ativas" on public.category;
create policy "Leitura pública de categorias ativas"
on public.category
for select
to anon, authenticated
using (active = true);

-- Catálogo público: somente leitura de produtos ativos
revoke all on table public.product from anon, authenticated;
grant select on table public.product to anon, authenticated;

drop policy if exists "Leitura pública de produtos ativos" on public.product;
create policy "Leitura pública de produtos ativos"
on public.product
for select
to anon, authenticated
using (active = true);

-- Imagens públicas somente quando o produto estiver ativo
revoke all on table public.product_image from anon, authenticated;
grant select on table public.product_image to anon, authenticated;

drop policy if exists "Leitura pública de imagens de produtos ativos" on public.product_image;
create policy "Leitura pública de imagens de produtos ativos"
on public.product_image
for select
to anon, authenticated
using (
    exists (
        select 1
        from public.product p
        where p.id = product_image.product_id
          and p.active = true
    )
);

commit;

-- Conferência opcional após executar:
-- select table_name
-- from information_schema.tables
-- where table_schema = 'public'
--   and table_name in ('admin', 'category', 'product', 'product_image')
-- order by table_name;
