-- Execute este arquivo no Supabase SQL Editor em projetos que já possuem as tabelas antigas.
begin;

create table if not exists public.category (
    id integer generated by default as identity primary key,
    name varchar(80) not null unique,
    slug varchar(100) not null unique,
    description text default '',
    active boolean default true,
    sort_order integer default 0,
    created_at timestamp without time zone default now()
);

create index if not exists idx_category_active_order
    on public.category(active, sort_order, name);

-- Migra automaticamente as categorias que já existem nos produtos.
insert into public.category (name, slug, active, sort_order)
select distinct
    trim(category),
    lower(regexp_replace(regexp_replace(trim(category), '[^a-zA-Z0-9]+', '-', 'g'), '(^-|-$)', '', 'g')),
    true,
    0
from public.product
where category is not null
  and trim(category) <> ''
on conflict (name) do nothing;

alter table public.category enable row level security;
revoke all on table public.category from anon, authenticated;
grant select on table public.category to anon, authenticated;

drop policy if exists "Leitura pública de categorias ativas" on public.category;
create policy "Leitura pública de categorias ativas"
on public.category
for select
to anon, authenticated
using (active = true);

commit;
